apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - chart: grafana
        repoURL: https://grafana.github.io/helm-charts
        version: "9.4.5"
        namespace: test
      - chart: sealed-secrets
        repoURL: https://charts.bitnami.com/bitnami
        version: "2.5.19"
        namespace: sealed-secrets
      - chart: renovate
        repoURL: https://docs.renovatebot.com/helm-charts
        version: "43.53.2"
        namespace: renovate
      - chart: traefik
        repoURL: https://traefik.github.io/charts
        version: "37.1.1"
        namespace: traefik
  template:
    metadata:
      name: '{{chart}}'
    spec:
      project: default
      sources:
      - repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
          - $values/manifests/values/{{chart}}.yaml
      - repoURL: https://github.com/wmag19/homelab.git
        targetRevision: HEAD
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifests
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/wmag19/homelab.git
      revision: HEAD
      directories:
      - path: manifests/*
      - path: manifests/values
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/wmag19/homelab.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true