---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ghcr-pull-secret
  namespace: synology-csi
spec:
  encryptedData:
    .dockerconfigjson: AgBomgYM2q/kcVIaJG06rfM7VDLmg+hG3hXF9xmfMdVk8SvERCzFAiqiqgXylO/K+rbne+UtBM9coLFG3K2kPASw667G+wc0/6FY8pHS57Th0gmSjX1Of9QQcnO8YvQFJ7xjGWDxkKRkXIbikWGMAMpFQWaN5m6EGum0RruLhWTSyOHRxDuv5/8GHKRiu5iJtDIXYhbdPEl5lB7PgSrWS6ZtBcYJ1Y/OXJ0CDQSxn8F+2ln6U3BuOYd0FQ2fqrkDLC/tFNWwl8rdfb8lScz6aH3DVlkuQhVTifIFMi+kkGhDl8wCRbGpOgx5j824FDhxm82V37ZvSm09RF15sW8hdHfcJ21PAcDZ07hUF4nWwQtLw0boTrIIJSedW3CMWVVT9p4e9SkXoyPxs50n6+zGT+iWLcKlmcTs9ehg8xE/ekRSitRCvOB9RU8x3tBcIFe5ApQazhsl7ylgc+v77w9igzIqucQJA2yGXTR2Gy+1qqo+QT5j1/uUEpnyPLnaXG/KpEcBUrX0miBExdClBHqI0pRDgOC2KAelQDPXHvwujT6iHVROyizJ16h1EFFfTWaSW8z5Z5LDRXzO43KgLF5i3g6ASc/fXS7w14MuCN0mC6XOlTlaX6fITMhJBp0DqkETpvWC6GWwZlwdPS4LGf2uhTjY84Et+/8415i7HYmI7VSM4RWF/979JnZx4g65s+YvwXRQeCPQX08TCgjdjZIQaZW+ehmVV4/59WBKAj/5yr0edsa2WAArD0SDRg+ly7yk8bqdUQ+6Ih5PincqiuyOMFywpDRkcMKiuq6b2X2V9EJU5Eo7cCQHTQ/qeSb1ik1Ole/g2w0CHhG+dhhdj6h3MXKWyK7MSZTwgwkirw42HcfbNbJRd+AGXXqydqr91WpV9lAcPvCJZ88PRbm9iPytazUecBF/m4/42Oh/6U5SR1kN+L0mN01R1Hg3PHttSR+JnBpy5XAQx9LVNFB4WhrQfUbpJts6wuzFFGRtd38=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ghcr-pull-secret
      namespace: synology-csi
    type: kubernetes.io/dockerconfigjson
