apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info-template.yml: AgBi4p3RNRw/rKXCIwrgyTAOinE7bN3lebKrlin0wgNYFF4aL7eD9V9aH0Qj69wacs8iYiVAaMI8f6XchxhlSTLfat/dUkDF3bbeoGo7MdRUhDBwRx4jNuGbuMNqZggUAomrzx4vFuHUTIQdZ4gHkn20gYShUY+q2Ec8x7J6NB0TSZAsnkGT4SENRU9CVPjbC1FMAbmZceWAIFCBPidPeak+WSdIz8bMFSCO6Lgf+0zglQZQc0//7Ll5X8SN1q4J80ZULSf1mFg1rh25M24TFDhsYRdBlaS1uVHnU7QLkc8v6OOmPnP6HnklCVw8p/JUwgXMQvW0c0yBKj6chbpHNhqI/Pk8B4iV7XnJO8NhDDnDLGaYvBT8l3uJ93DAdYsEMQFpK6+iQX6IJRfvYVOJKVJikmHi9TsKCfsu2s/QSUSDK7WbGbNd+/mmlVXbOg+Rakl73Mvv0UFPmrDMFV/BQCXCScb8RtUpMnVnIozVKUNoq1ag9lNa1gApdNTOmOeqn2fg2tZFv/ff3G0jyvLrPw2c295I8GBu5z8NCssFDbSwR4GnVe2ic+0BiNNR7OXMwS+iD4JkYoiG2Lon99WNwpdPhx6iRSKU7RXZqrukdN89YLBH7mkzUAG3XLPmfprxzod1Bi569zZoWcqGfkZirPNmHCToQJ4K5JXspOQ1lbHEBB9H8t1NnYi7gSc4VVZGn1pKmhfIECwr+z168FTuePa645NYJmMnkLVHkPd5QiUu00CDQbjyWtTClkiLbO3/aXEc9S+rFMz5Wiyx6QNGgGd8EcTuh0S4rCvtzgxfJoM6NChsFwasE1bHBBtMkDvBaC85+ZBBPz5xKXHThCJoE6JWfDtMLdyBoMbAtd9NeHgL
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi